import type { Metadata } from "next";
import { Quattrocento, Quattrocento_Sans } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Foot from "@/components/Foot";

const qs = Quattrocento_Sans({ weight: "400", subsets: ["latin"] });
const q = Quattrocento({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eshop Front",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={qs.className}>
        <div
          className={`${q.className} bg-black w-full  text-center py-2 text-stone-300 text-base`}
        >
          Welcome to our store
        </div>

        <Navigation />
        {children}
        <Foot />
      </body>
    </html>
  );
}
